#!/usr/bin/env python3
"""Molecule-level PoseBusters worker: stage 2 after scripts/sbatch_pb_claim.sh.

WHY. sbatch_pb_claim.sh claims whole pockets and runs each pocket's molecules serially on one core.
That is right when slow molecules are rare, and wrong for IPDiff and AliDiff. Some of their pockets
hold dozens of molecules whose internal_energy check runs for hundreds of seconds. Measured
2026-09-13: ipdiff pocket012 timed out (900 s) on its first two molecules in a row, and 34 in-flight
pockets projected past 2 h, which overruns a 3 h job and loses the whole pocket. Here the unit is
ONE MOLECULE, so a pocket's wall time is its slowest molecule rather than the sum of them.

QUEUE, all on the shared filesystem, per model:
  <root>/<m>/posebusters/.pending/pocketNNN/mXXXX.sdf         waiting (built by pb_finalize.py --queue)
  <root>/<m>/posebusters/.running/pocketNNN/mXXXX.sdf.job<ID> claimed: atomic rename out of .pending
  <root>/<m>/posebusters/.results/pocketNNN/mXXXX.sdf.csv      PoseBusters output (header + 1 row)
  <root>/<m>/posebusters/.results/pocketNNN/mXXXX.sdf.fail     timeout or error: rc, secs, threads
A claim whose owner job has left squeue is renamed back into .pending by the next worker to start.
This worker never writes pocketNNN.csv / .timeouts / .done. pb_finalize.py --finalize does that.

METHOD. Same bust call as sbatch_pb_claim.sh: dock mode, --outfmt csv, 900 s timeout, one process per
molecule. It passes --config configs/posebusters_dock_<T>thread.yml, which differs from the 1-thread
yml only in num_threads. That sets RDKit's thread count for the SEEDED ETKDG ensemble
(randomSeed=42). It changes how long a heavy molecule takes, not what it returns: all 114
full-report columns matched on 12 molecules between the default thread count and 1. The job runs
floor(cpus / T) molecules at a time.

TWO PASSES (2026-09-13). Pass 1 runs PB_THREADS=1 PBTIMEOUT=120: the light majority finishes in
1-15 s, and its output does not depend on the thread count. A .fail from pass 1 records timeout=120
and is NOT final. pb_finalize.py --queue --retry-short-fails sends it back for pass 2 under the full
900 s budget, and --finalize never treats a fail with timeout < 900 as an exclusion.

Env: MODELS, PB_THREADS (default 4), PBTIMEOUT (900), EVAL_ROOT (eval_out), SLURM_CPUS_PER_TASK.
Run through scripts/sbatch_pb_mol.sh.
"""
import atexit
import csv
import glob
import os
import random
import shutil
import signal
import socket
import subprocess
import sys
import tempfile
import threading
import time
from concurrent.futures import ThreadPoolExecutor

# Derive the repository root instead of hardcoding it, so the worker runs from a clone.
ROOT = os.environ.get('REPO') or os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
EVAL_ROOT = os.environ.get('EVAL_ROOT', 'eval_out')
MODELS = os.environ.get('MODELS', 'pocket2mol ipdiff alidiff molcraft').split()
# PoseBusters lives in its own environment; see envs/environment-posebusters.yml.
BUST = os.environ.get(
    'BUST', os.path.join(os.environ.get('CONDA_BASE', os.path.expanduser('~/anaconda3')),
                         'envs', 'ged-posebusters', 'bin', 'bust'))
TIMEOUT = int(os.environ.get('PBTIMEOUT', '900'))
CPUS = int(os.environ.get('SLURM_CPUS_PER_TASK', '4'))
THREADS = int(os.environ.get('PB_THREADS', '4'))
NPROC = max(1, CPUS // THREADS)
JOB = os.environ.get('SLURM_JOB_ID', f'local{os.getpid()}')
# PB_QUEUE_TAG=heavy -> .pending_heavy/.running_heavy. Pass-2 molecules get their own queue, so a pass-1
# worker (120 s budget) running at the same time can never claim one and fail it again.
QTAG = os.environ.get('PB_QUEUE_TAG', '')
PENDING = '.pending' + (f'_{QTAG}' if QTAG else '')
RUNNING = '.running' + (f'_{QTAG}' if QTAG else '')
HOST = socket.gethostname()
BASE_CFG = 'configs/posebusters_dock_1thread.yml'
LIVE_STATES = ('RUNNING', 'PENDING', 'CONFIGURING', 'COMPLETING', 'SUSPENDED', 'RESIZING',
               'SIGNALING', 'STAGE_OUT')
for k in ('OMP_NUM_THREADS', 'MKL_NUM_THREADS', 'OPENBLAS_NUM_THREADS', 'NUMEXPR_NUM_THREADS'):
    os.environ[k] = '1'

LOCK = threading.Lock()
STATS = {'ok': 0, 'fail': 0}
_alive = {}


def log(msg):
    print(f'{time.strftime("%H:%M:%S")} {msg}', flush=True)


def pb_dir(m):
    return f'{EVAL_ROOT}/{m}/posebusters'


def config_for(threads):
    """configs/posebusters_dock_<T>thread.yml, generated from the 1-thread yml if missing."""
    if threads == 1:
        return BASE_CFG
    path = f'configs/posebusters_dock_{threads}thread.yml'
    if not os.path.exists(path):
        s = open(BASE_CFG).read()
        assert s.count('      num_threads: 1\n') == 1, BASE_CFG
        s = s.replace('      num_threads: 1\n', f'      num_threads: {threads}\n')
        note = (f'# GENERATED by scripts/pb_mol_worker.py from {BASE_CFG}; identical except '
                f'num_threads: {threads}. The header below describes the 1-thread original.\n')
        tmp = f'{path}.tmp.{JOB}'
        with open(tmp, 'w') as fh:
            fh.write(note + s)
        os.replace(tmp, path)
    return path


def receptors():
    rec = {}
    for m in MODELS:
        with open(f'{EVAL_ROOT}/{m}/manifest.csv') as fh:
            for r in csv.DictReader(fh):
                rec[(m, int(r['pocket_idx']))] = r['receptor'].strip()
    return rec


def alive(job):
    """True if the job may still hold its claims. Unknown squeue failures count as alive."""
    if job == JOB or job.startswith('local'):
        return True
    hit = _alive.get(job)
    if hit and time.time() - hit[1] < 60:
        return hit[0]
    r = subprocess.run(['squeue', '-h', '-j', job, '-o', '%T'], capture_output=True, text=True)
    if r.returncode != 0:
        ok = 'Invalid job id' not in (r.stdout + r.stderr)
    else:
        st = r.stdout.strip()
        ok = st in LIVE_STATES or st.startswith('REQUEUE')
    _alive[job] = (ok, time.time())
    return ok


def sweep_stale():
    """Return claims of departed jobs to .pending, and drop their /tmp work dirs on this node."""
    n = 0
    for m in MODELS:
        for f in glob.glob(f'{pb_dir(m)}/{RUNNING}/pocket*/*.sdf.job*'):
            base, owner = f.rsplit('.job', 1)
            if alive(owner):
                continue
            dst = f'{pb_dir(m)}/{PENDING}/{os.path.basename(os.path.dirname(f))}/{os.path.basename(base)}'
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            try:
                os.rename(f, dst)
                n += 1
            except FileNotFoundError:
                pass
    for w in glob.glob('/tmp/pbm_*_*'):
        owner = os.path.basename(w).split('_')[1]
        if owner != JOB and not alive(owner):
            shutil.rmtree(w, ignore_errors=True)
    if n:
        log(f'requeued {n} molecules claimed by departed jobs')


_cands = []


def rescan():
    out = []
    for m in MODELS:
        for d in glob.glob(f'{pb_dir(m)}/{PENDING}/pocket*'):
            try:
                names = os.listdir(d)
            except FileNotFoundError:
                continue
            out += [(m, os.path.basename(d), n) for n in names if n.endswith('.sdf')]
    random.shuffle(out)      # jobs start at different places instead of racing for the same files
    return out


def claim():
    global _cands
    with LOCK:
        for _ in range(2):
            while _cands:
                m, pocket, name = _cands.pop()
                src = f'{pb_dir(m)}/{PENDING}/{pocket}/{name}'
                dst = f'{pb_dir(m)}/{RUNNING}/{pocket}/{name}.job{JOB}'
                os.makedirs(os.path.dirname(dst), exist_ok=True)
                try:
                    os.rename(src, dst)
                    return m, pocket, name, dst
                except FileNotFoundError:
                    continue
            _cands = rescan()
            if not _cands:
                return None
    return None


def write_atomic(path, text):
    tmp = f'{path}.tmp.{JOB}.{threading.get_ident()}'
    with open(tmp, 'w') as fh:
        fh.write(text)
    os.replace(tmp, path)


def run_one(item, rec, cfg):
    m, pocket, name, claimed = item
    resdir = f'{pb_dir(m)}/.results/{pocket}'
    os.makedirs(resdir, exist_ok=True)
    work = tempfile.mkdtemp(prefix=f'pbm_{JOB}_', dir='/tmp')
    local = os.path.join(work, name)          # keep mXXXX.sdf: bust picks the reader by extension
    shutil.copyfile(claimed, local)
    t0 = time.time()
    r = subprocess.run(['timeout', str(TIMEOUT), BUST, local, '-p', rec[(m, int(pocket[6:]))],
                        '--outfmt', 'csv', '--config', cfg],
                       stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True)
    secs = time.time() - t0
    if r.returncode == 0 and len(r.stdout.strip().splitlines()) >= 2:
        write_atomic(f'{resdir}/{name}.csv', r.stdout)
        state = 'ok'
    else:
        write_atomic(f'{resdir}/{name}.fail',
                     f'rc={r.returncode} secs={secs:.0f} threads={THREADS} timeout={TIMEOUT} job={JOB} host={HOST}\n')
        state = 'fail'
    try:
        os.remove(claimed)
    except FileNotFoundError:
        pass
    shutil.rmtree(work, ignore_errors=True)
    return state, secs, r.returncode


def worker(slot, rec, cfg):
    while True:
        item = claim()
        if item is None:
            return
        state, secs, rc = run_one(item, rec, cfg)
        with LOCK:
            STATS[state] += 1
            done = STATS['ok'] + STATS['fail']
        if state == 'fail' or secs > 120:
            log(f'[w{slot}] {item[0]} {item[1]} {item[2]} {state} rc={rc} {secs:.0f}s')
        if done % 200 == 0:
            log(f'progress {STATS}')


def cleanup(*_):
    for w in glob.glob(f'/tmp/pbm_{JOB}_*'):
        shutil.rmtree(w, ignore_errors=True)


def main():
    atexit.register(cleanup)
    signal.signal(signal.SIGTERM, lambda *a: (cleanup(), sys.exit(143)))
    cfg = config_for(THREADS)
    rec = receptors()
    log(f'job={JOB} host={HOST} cpus={CPUS} threads={THREADS} procs={NPROC} timeout={TIMEOUT}s '
        f'config={cfg} queue={PENDING} models={MODELS} root={EVAL_ROOT}')
    sweep_stale()
    with ThreadPoolExecutor(NPROC) as ex:
        for f in [ex.submit(worker, i, rec, cfg) for i in range(NPROC)]:
            f.result()
    log(f'PB_MOL_WORKER_DONE {STATS}')


if __name__ == '__main__':
    main()
